<?php

/**
 * @file
 * Primary module hooks for Dynamic Site location and time module.
 *
 * @DCG
 * This file is no longer required in Drupal 8.
 * @see https://www.drupal.org/node/2217931
 */

/**
 * Implements hook_theme().
 */
function dynamic_site_location_and_time_theme() {
  return [
    'current_location_time' => [
      'variables' => [
        'country' => NULL,
        'city' => NULL,
        'time' => NULL,
        'timezone' => NULL,
      ],
    ],
  ];
}

